/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'timbo' at '8/22/15 7:03 PM' with Gradle 2.2.1
 *
 * @author timbo, @date 8/22/15 7:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
